modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="mod_zelda"
version="1.0.0"
displayName="mod zelda"
credits="KOryxTV,Zeiirox, secretwars"
displayURL="https://mcreator.net"
authors="passo, MCreator"

[[dependencies.mod_zelda]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




